##' @title QC Detection QC test
##'
##' @description ...
##' 
##' @param qc_results the `temporal_outcome` object, holding all QC test results, 
##' generated by `remora::qc`
##' 
##' @details ...
##' 
##' @return adds final Detection QC test outcomes to temporal_outcome object
##' 
##' @keywords internal
##' 
qc_detection_qc <- function(qc_result, data_format = "imos") {
  print("Running detection QC")
  ## IDJ - this mimics original remora Detection QC only tests 1:5 are summed,
  ##       but accounts for tests that are turned off and not in qc_result
  if(data_format == "imos") {
    idx <- which(names(qc_result) %in% 
                   c("FDA_QC",
                     "Velocity_QC",
                     "Distance_QC",
                     "DetectionDistribution_QC",
                     "DistanceRelease_QC",
                     "ReleaseDate_QC",
                     "ReleaseLocation_QC"
                   ))
    
    ones <- rowSums(qc_result[, idx] == 1)
    
    qc_result[which(ones <= 2), "Detection_QC"] <- 4
    qc_result[which(ones == 3), "Detection_QC"] <- 3
    qc_result[which(ones == 4), "Detection_QC"] <- 2
    qc_result[which(ones >= 5), "Detection_QC"] <- 1
    if("Velocity_QC" %in% idx) {
      qc_result$Velocity_QC <- as.numeric(qc_result$Velocity_QC)
    }
    if("Distance_QC" %in% idx) {
      qc_result$Distance_QC <- as.numeric(qc_result$Distance_QC)
    }
  }
  #BD: With OTN detection extracts, we will have already QC'd for Release Date and Release Location, so we shouldn't count them towards the aggregation
  #even if they've been run. 
  else if(data_format == "otn") {
    idx <- which(names(qc_result) %in% 
                   c("FDA_QC",
                     "Velocity_QC",
                     "Distance_QC",
                     "DetectionDistribution_QC",
                     "DistanceRelease_QC"
                   ))
    
    ones <- rowSums(qc_result[, idx] == 1)
    total_tests <- ncol(qc_result)
    
    #Set everything to be 1 and then reassign as below. 
    qc_result[,"Detection_QC"] <- 1
    qc_result[which(ones/total_tests < 0.75), "Detection_QC"] <- 2
    qc_result[which(ones/total_tests < 0.50), "Detection_QC"] <- 3
    qc_result[which(ones/total_tests < 0.25), "Detection_QC"] <- 4
    if("Velocity_QC" %in% idx) {
      qc_result$Velocity_QC <- as.numeric(qc_result$Velocity_QC)
    }
    if("Distance_QC" %in% idx) {
      qc_result$Distance_QC <- as.numeric(qc_result$Distance_QC)
    }
  }

  return(qc_result)
}