##' title Release Location test
##'
##' @description ...
##' 
##' @param data data formatted by either `remora::get_data` or `remora::get_data_arbitrary`
##' @param qc_result the `temporal_outcome` object, holding all QC test results, 
##' generated by `remora::qc`
##' @param species_range the expert species distribution shapefile (if avaiable)
##' @param distances ...
##' @param latlons ...
##' @param distance_threshold ...
##' 
##' @details ...
##' 
##' @return adds Detection Distribution test outcomes to temporal_outcome object
##' 
##' @importFrom sf as_Spatial
##' @keywords internal
##' 
qc_release_location_test <-
  function(data,
           qc_result,
           species_range,
           distances,
           latlons,
           distance_threshold = 500) {
    
    message("Starting release location test.")
    ## Release location test
    if (!is.null(species_range)) {
      message("We have a shapefile")
      species_range_spatial <- sf::as_Spatial(species_range)
      qc_result[, "ReleaseLocation_QC"] <-
        ifelse(distances[1] > distance_threshold &
                 sum(is.na(
                   sp::over(latlons, species_range_spatial, returnList = TRUE)
                 )) > 0, 2, 1)
    } else {
      message("We have no shapefile.")
      qc_result[, "ReleaseLocation_QC"] <-
        ifelse(distances[1] > distance_threshold, 2, 1)
    }
    message("release location test done")
    return(qc_result)
  }