##' @title QC Detection Distribution test
##'
##' @description ...
##' 
##' @param data data formatted by either `remora::get_data` or `remora::get_data_arbitrary`
##' @param latlons longlat coords of detections
##' @param qc_result the `temporal_outcome` object, holding all QC test results, 
##' generated by `remora::qc`
##' @param species_range the expert species distribution shapefile (if avaiable)
##' 
##' @details ...
##' 
##' @return adds Detection Distribution test outcomes to temporal_outcome object
##' 
##' @keywords internal
##' 
qc_test_det_distro <- function(data, latlons, qc_result, species_range) {
  qc_result[, "DetectionDistribution_QC"] <- ifelse(is.null(species_range), 3, 1)
  #View(latlons@coords)
  if(!is.null(species_range)) {
    out <- which(is.na(over(latlons, species_range)))
    #View(out)
    if(length(out) > 0) {
      qc_result[data$longitude %in% latlons@coords[out, 1] &
                         data$latitude %in% latlons@coords[out, 2], "DetectionDistribution_QC"] <- 2
    }
  }
  return(qc_result)
}