##' @title QC Detection Distribution test
##'
##' @description ...
##' 
##' @param data data formatted by either `remora::get_data` or `remora::get_data_arbitrary`
##' @param latlons longlat coords of detections
##' @param qc_results the `temporal_outcome` object, holding all QC test results, 
##' generated by `remora::qc`
##' @param species_range the expert species distribution shapefile (if avaiable)
##' 
##' @details ...
##' 
##' @return adds Detection Distribution test outcomes to temporal_outcome object
##' 
##' @importFrom sf as_Spatial
##' @keywords internal
##' 
qc_test_det_distro <- function(data, 
                               latlons, 
                               qc_results, 
                               species_range) {
  
  qc_results[, "DetectionDistribution_QC"] <- ifelse(is.null(species_range), 3, 1)
  
  #Make a spatial object out of the lat/lon. These steps may not be necessary when running the IMOS version. Also
  #gotta find a way around that hardcoding. 
  #coordinates(latlons) <- c("x.longitude", "x.latitude")
  #proj4string(latlons) <- CRS("+proj=longlat +datum=WGS84")
  if(!is.null(species_range)) {
    print("Need to do some debug in det distro")
    print(over(latlons, as_Spatial(species_range)))
    out <- which(is.na(over(latlons, as_Spatial(species_range))))
    print(out)
    if(length(out) > 0) {
      qc_results[data$longitude %in% latlons@coords[out, 1] &
                         data$latitude %in% latlons@coords[out, 2], "DetectionDistribution_QC"] <- 2
    }
  }
  return(qc_results)
}