##' @title QC velocity test
##'
##' @description QC test for unrealistic velocity between acoustic detections. 
##' Requires at least two detections present in detections data.
##' 
##' @param data data formatted by either `remora::get_data` or `remora::get_data_arbitrary`
##' @param qc_results the `temporal_outcome` object, holding all QC test results, 
##' generated by `remora::qc`
##' @param dist output from `remora::shortest_dist`
##' 
##' @details ...
##' 
##' @return adds Velocity test outcomes to temporal_outcome object
##' 
##' @importFrom lubridate as.difftime
##' 
##' @keywords internal
##' 
qc_test_velocity <- function(data, qc_results, dist, velocity_threshold = 10) {
  
  if (length(dist) == 1) {
      timediff <- as.numeric(
        as.difftime(
          data$detection_datetime - data$transmitter_deployment_datetime,
          tz = "UTC",
          units = "secs"
        )
      )
      
      velocity <-(dist * 1000) / timediff 
      qc_results["Velocity_QC"] <- ifelse(velocity <= velocity_threshold, 1, 2)
  } 
  
  else if (length(dist) > 1) {
    dist_next <- c(dist[2:nrow(dist)], NA)
    
    time <-
      c(data$transmitter_deployment_datetime[1],
        data$detection_datetime)
    
    timediff <-
      abs(
        as.numeric(
        as.difftime(
          time[2:length(time)] - time[1:(length(time) - 1)],
          tz = "UTC", 
          units = "secs"
      )))
    timediff_next <- c(timediff[2:length(timediff)], NA)
    
    ## Exception to overcome the fact that a same tag may be detected by
    ##  two neighbouring stations at the exact same time, thus creating
    ##  infinite velocity values
    timediff[which(timediff == 0)] <- 1
    timediff_next[which(timediff_next == 0)] <- 1
    velocity <- (dist * 1000) / timediff
    velocity_next <- (dist_next * 1000) / timediff_next
    
    ## Velocity test
    qc_results[, 'Velocity_QC'] <- ifelse(velocity > velocity_threshold & velocity_next > velocity_threshold, 2, 1)
    qc_results[1, 'Velocity_QC'] <- ifelse(velocity[1] > velocity_threshold, 2, 1)
    qc_results[nrow(data), 'Velocity_QC'] <- ifelse(velocity[nrow(data)] > velocity_threshold, 2, 1)
  }
  return(qc_results)
}