##' @title QC Distance Release test
##'
##' @description ...
##' 
##' @param data data formatted by either `remora::get_data` or `remora::get_data_arbitrary`
##' @param qc_results the `temporal_outcome` object, holding all QC test results, 
##' generated by `remora::qc`
##' 
##' @details ...
##' 
##' @return adds Distance Release test outcomes to temporal_outcome object
##' 
##' @importFrom geosphere distGeo
##' 
##' @keywords internal
##' 
qc_test_dist_release <- function(data, qc_results) {
  if("transmitter_deployment_longitude" %in% colnames(data) &&
     "transmitter_deployment_latitude" %in% colnames(data)) {
    dist_r <- distGeo(cbind(data$transmitter_deployment_longitude[rep(1, nrow(data))],
                            data$transmitter_deployment_latitude[rep(1, nrow(data))]),
                      cbind(data$longitude, data$latitude)) / 1000 ## return in km
    qc_results[, "DistanceRelease_QC"] <- ifelse(dist_r > 500, 2, 1)
  } else {
    message("No transmitter lat/long in dataframe, skipping distance-from-release check.")
  }
  return(qc_results)
}